[package]
name = "te"
version = "0.1.0"
description = "A really simple, stripped down & readable regular expression alternative for matching text"
authors = ["schulke-214 <hello@maximilianschulke.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
pretty_assertions = "0.6.1"